### ISSUE TITLE
"failed to lookup address information" exception on index download

### ISSUE THREAD

**Issue by flit** [ARMmbed/cmsis-pack-manager#88]
I'm seeing this exception when I either run `pack-manager cache pdsc` or directly call `Cache.cache_descriptors()`. I've tried running `pack-magager cache rm` prior to attempting again, to no avail.

```
Io(Custom { kind: Other, error: StringError("failed to lookup address information: nodename nor servname provided, or not known") })
Traceback (most recent call last):
  File "/Users/creed/projects/pyOCD-flit/venv/mac37/bin/pack-manager", line 10, in <module>
    sys.exit(main())
  File "/Users/creed/projects/pyOCD-flit/venv/mac37/lib/python3.7/site-packages/cmsis_pack_manager/pack_manager.py", line 235, in main
    args.command(args)
  File "/Users/creed/projects/pyOCD-flit/venv/mac37/lib/python3.7/site-packages/cmsis_pack_manager/pack_manager.py", line 94, in thunk
    return command(cache, **argv)
  File "/Users/creed/projects/pyOCD-flit/venv/mac37/lib/python3.7/site-packages/cmsis_pack_manager/pack_manager.py", line 134, in command_cache
    cache.cache_descriptors()
  File "/Users/creed/projects/pyOCD-flit/venv/mac37/lib/python3.7/site-packages/cmsis_pack_manager/__init__.py", line 287, in cache_descriptors
    pdsc_index = self._call_rust_update(progress_fn)
  File "/Users/creed/projects/pyOCD-flit/venv/mac37/lib/python3.7/site-packages/cmsis_pack_manager/__init__.py", line 259, in _call_rust_update
    pdsc_index = lib.update_pdsc_result(poll_obj)
  File "/Users/creed/projects/pyOCD-flit/venv/mac37/lib/python3.7/site-packages/cmsis_pack_manager/__init__.py", line 35, in __exit__
    raise Exception(ffi.string(maybe_err))
Exception: b'\nfailed to lookup address information: nodename nor servname provided, or not known'
```

**Comment by theotherjimmy** [comment]
Oh weird. I don't know what would cause this off the top of my head.
